### ISSUE TITLE
Limitation of constraint names longer than 64 characters

### ISSUE THREAD

**Issue by jandert2019** [spryker-eco/braintree#20]
This is a problem for schema file spy_braintree.schema.xml:
`spy_braintree_transaction_status_log-fk_payment_braintree_order_item`
in `<foreign-key name="spy_braintree_transaction_status_log-fk_payment_braintree_order_item" foreignTable="spy_payment_braintree_order_item">
            <reference foreign="id_payment_braintree_order_item" local="fk_payment_braintree_order_item"/>
        </foreign-key>`

and `spy_payment_transaction_order_item-fk_payment_braintree_order_item` in 
`<foreign-key name="spy_payment_transaction_order_item-fk_payment_braintree_order_item" foreignTable="spy_payment_braintree_order_item">
            <reference foreign="id_payment_braintree_order_item" local="fk_payment_braintree_order_item"/>
        </foreign-key>`

propel:migrate is then constantly trying to remove the shortened name and recreating the too long one.

**Comment by tvaleriy** [comment]
Hi @jandert2019,

thank you for notifying. This is already known issue and the fix is in development at the moment.
Please follow new releases here.

Also next time please create issue reports here - https://support.spryker.com/hc/en-us/requests/new.

Thanks and have a good day!

Best,
Spryker Support Team
